# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of Python requirements (requirements*.txt, pyproject)
    schedule:
      interval: "daily"
    groups:
      prod-deps:
        patterns:
          - "fastapi"
          - "uvicorn"
          - "pydantic*"
          - "pydantic-settings"
          - "httpx"
          - "PyYAML"
          - "python-dotenv"
          - "tenacity"
          - "apscheduler"
          - "prometheus-client"
      dev-deps:
        patterns:
          - "black"
          - "ruff"
          - "isort"
          - "mypy"
          - "types-*"
          - "bandit"
          - "pytest"
          - "pytest-*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions:
        patterns:
          - "*"
