[tool.black]
line-length = 100
target-version = ["py39"]

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true
force_sort_within_sections = true

[tool.ruff]
line-length = 100
target-version = "py39"
extend-exclude = [".venv", "node_modules"]

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "I", "C90"]
ignore = ["UP007"]

[tool.ruff.lint.mccabe]
max-complexity = 20
